### ISSUE TITLE
레이싱 콘텐츠

### ISSUE THREAD

**Issue by aespablo** [envybros/nomads-planet#14]
[에셋 연구](https://assetstore.unity.com/packages/templates/systems/highroad-engine-73798)

나도 모르게 구매했던 것 같다.
그런데 지금 콘텐츠에 잘 어울리는 것 같아서.. 어느 정도 고려는 해보자.

**Comment by pulp-pixel** [comment]
존나 아쉽게도 시간 관계상 못할 것 같음.. (경진대회 끝나고 개별적으로 해도 될듯)
