### ISSUE TITLE
MenuScene Update

### ISSUE THREAD

**Issue by pulp-pixel** [envybros/nomads-planet#48]
여기 스플레툰이나 몬헌처럼, 여러 활동들 할 수 있게 하자

- 차 꾸미기나 캐릭터 꾸미기를 여기서 할 수 있도록 하기
- 친구나 편지 시스템도 가능하면 도입
- 여기서는 차 타지 말고 뛰어댕기기

친구 초대 및 꾸미기 콘텐츠도 가능하면 여기 들어가면 좋을듯?

아니면 방은 따로 씬을 파서 만들어도?

**Comment by pulp-pixel** [comment]
이거 굉장히 좋은 아이디어고, TimeLine 활용해서,, 씬 시작마다 좀 친절하게 가자.

**Comment by pablo-stelsi** [comment]
MenuScene부터 해서 GameScene까지.. Cinemachine <- 이거 제대로 활용해서 시퀀스 찍어야 할 것 같아

**Comment by pulp-pixel** [comment]
이게 시벌 지금 이래 멈춰있을만한 일이야???

Cinemachine 등등 해서 빨리 찍어
