### ISSUE TITLE
Vivox 도입

### ISSUE THREAD

**Issue by pablo-stelsi** [envybros/nomads-planet#51]

**Comment by pulp-pixel** [comment]
캐릭터 카메라 움직임 겁나 느리게 움직이게 하기

마우스로 UI를 조작해야 하는데, 카메라 이동이 빠르면 너무 부자연스러움

**Comment by pulp-pixel** [comment]
Vivox 도입 이거 생각보다 쉬워보임

**Comment by pulp-pixel** [comment]
방금 생각난 거. 

채팅 및 범퍼카 메뉴 들어갔을 때, BGM 바꾸자. 

엄연한 콘텐츠니까

**Comment by pulp-pixel** [comment]
Vivox sample <-- 이거 Plugin 폴더에 넣기
