### ISSUE TITLE
Whole Map Level Design (Menu Scene)

### ISSUE THREAD

**Issue by pulp-pixel** [envybros/nomads-planet#54]

**Comment by pulp-pixel** [comment]
애니메이션하고, 배경음악 바꾸기?

**Comment by pulp-pixel** [comment]
Ui파티클 + ui 사운드 등등 엄청 많이 꾸미기 (과할 정도로)

**Comment by pulp-pixel** [comment]
게임씬 다녀와서, 돈 벌어왔다면, UI 파티클 이용해서 값 업데이트 치자.

꼭 게임씬에서 업데이트 할 필요는 없다.

**Comment by pulp-pixel** [comment]
채팅 들어갔을 때, 범퍼카 메뉴 들어갔을 때 전부 BGM 바꾸기,
전체적인 BGM 및 SFX 손보기

**Comment by pulp-pixel** [comment]
호스트도 그렇고 로비도 그렇고 넘어가기 전에, 캐릭터 사라지는 모션 있으면 더 좋을듯

그리고 맵 시작 전에 캐릭터 하강하고 있는 타임라인 만들고, 캐릭터 먼저 내려가고, 그 후
시네머신 카메라 이동으로 확! 이동시키기

**Comment by pulp-pixel** [comment]
스플레시 이미지도 넣어

**Comment by pulp-pixel** [comment]
씬 이동 화면 너무 못생겼나?

**Comment by pulp-pixel** [comment]
시네마틱 영상처럼 가면 됨

#SEQ1

처음에 차량 잠깐 잠깐 보여주면서 로고도 뜨고, 이름도 보여주고 (아이콘x, 텍스트로만), (이거 전에 캐릭터 보여주다가 오디오 재생버튼 누르는 듯한 애니메이션 넣어주면 될듯) 차고에서 나오기 -> 그러면서 다시 페이드 아웃/인

#SEQ2

밝아지면서 차량 계속 따라가기

물체랑 부딪히기 전에,, 카메라 위치 변경 후 슬로우모션 (슬로우모션으로 부딪히면서, 물체들 날아가는 거 보여주기)

그리고 골목길로 차가 여기저기 부딪히고 가면서 위와 비슷하게 쓰레기통 다 엎어짐 (탑뷰로 따라가기)

마지막 골목 돌 때, 캐릭터 윙크하는 거 포커스 및 슬로우모션

#SEQ3

차량은 직진 방향으로 쭉 나아가고, 카메라 고정 및 Y축으로 올라가면서 페이드 아웃/인

#SEQ4

차량에 기대고 있는 캐릭터 + Idle Anim + 중간 중간 표정 변화 도입 + 파티클 추가 (월페이퍼 엔진 느낌) -> 여기 맵은 커브드 월드 넣어줘도 되려나?

+ 여기가 UI 버튼 누르는 공간 (사펑 느낌나게 만들면 될 것 같은데,, 전체적인 색깔과 달라지면 안돼)

**Comment by pulp-pixel** [comment]
대신 이 모든건 서버에서는 꺼두기

**Comment by pulp-pixel** [comment]
게임씬 이전에 떨어지는 모션 + 타임라인 조금 넣기

게임씬 이후, Ui파티클 통해 축하 효과 넣기

메뉴로 사운드 조절 옵션 넣어줘야할듯 (GlobalSounManager)

로딩씬 디자인 좀 바꾸자 (그 퍼플 오렌지로 가도 될듯)

**Comment by pulp-pixel** [comment]
Localization 적용하는 김에, 한국어 보이스도 해보고 (안되면 빠른 포기) 범퍼카 게임에 약간의 안내문구 추가해주기 (처음 캐릭터 떨어지는 모션 때 해도 될듯)

**Comment by pulp-pixel** [comment]
트레일러 다시 보기 버튼

**Comment by pulp-pixel** [comment]
거의 다 옴

Bootstrap 씬에서 마지막 ui부분에 파티클 넣을 만한 거 있으면 넣기 (metamask 처럼?)

전체적인 BGM 손보기

---

각종 버그는 새로 issue파서 고쳐보기 (오늘 QA까지 다 하고 자야함)

**Comment by pulp-pixel** [comment]
부트스트랩씬 마지막에 브레이크 소리는 좀 넣어줘야 할 것 같음

**Comment by pulp-pixel** [comment]
한글하고 영어 버튼에도 각각 나라별 보이스에 맞게,, 음성 재생 (이건 로컬라이제이션 적용하면 안됨)

**Comment by pablo-stelsi** [comment]
전체적으로 BGM 볼륨들은 낮게 설정하기
+ 빗소리 너무 큼,, 천둥 소리 또한 마찬가지

**Comment by pablo-stelsi** [comment]
처음 인트로 때, "ENVY BROS Present" 문구 넣어줘야함
